proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::index

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::entreprises

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::formations

proStage_stage:
    path: /stage/{id}
    controller: App\Controller\ProStageController::stage

proStage_entreprise:
    path: /entreprises/{id}
    controller: App\Controller\ProStageController::entreprise

proStage_formation:
    path: /formations/{id}
    controller: App\Controller\ProStageController::formation